# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QUIZ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QUIZ
  pod 'SCLAlertView'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Alamofire'
  pod 'SDWebImage' 
  pod 'RxSwift'
  pod 'RxCocoa'
end
